#!/bin/bash
sudo systemctl stop docker
sudo mkdir -p /etc/systemd/system/docker.service.d
sudo chmod -R 777 /etc/systemd/system/docker.service.d
echo "[Service]" > /etc/systemd/system/docker.service.d/selinux.conf
echo "Environment=DOCKER_SELINUX=--selinux-enabled=false" >> /etc/systemd/system/docker.service.d/selinux.conf
sudo systemctl daemon-reload && sudo systemctl enable docker && sudo systemctl restart docker
