#!/bin/bash

link="socks5://127.0.0.1:1080"

proxy=$link \
http_proxy=$link \
https_proxy=$link \
ftp_proxy=$link \
rsync_proxy=$link \
all_proxy=$link \
no_proxy="localhost,127.0.0.1,localaddress,.localdomain.com" \
server_proxy=$link \
PROXY=$link \
HTTP_PROXY=$link \
HTTPS_PROXY=$link \
FTP_PROXY=$link \
RSYNC_PROXY=$link \
ALL_PROXY=$link \
NO_PROXY="localhost,127.0.0.1,localaddress,.localdomain.com" \
SERVER_PROXY=$link \
$*
