#! /bin/bash
sudo mv /home/core/.bashrc /home/core/.bashrc.bak
cp /home/core/docker/shell/bashrc /home/core/.bashrc
sudo mv /root/.bashrc /root/.bashrc.bak
sudo cp /home/core/docker/shell/bashrc /root/.bashrc
export PATH="/home/core/docker/shell:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/bin:$PATH"

