# see https://github.com/docker-library/rabbitmq/blob/af5f6ff9a3916d89be6d190d562d247ae12ffa73/3.8/ubuntu/management/Dockerfile
# see https://github.com/docker-library/rabbitmq/blob/4a563bd82fe53b46b144d5ee17af6627ff34af65/3.8/ubuntu/Dockerfile
FROM rabbitmq:3.8.0-management-alpine

